tango_with_django_project/rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_url>\w+)/add_page/$',
        views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_url>\w+)/$',
        views.category, name='category'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/', views.restricted, name='restricted'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^goto/$', views.track_url, name='track_url'),
    url(r'^like_category/$', views.like_category,name='like_category'),
    url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
)

tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tango_with_django_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls', namespace='rango')), # ADD
                       # THIS NEW TUPLE!
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
         'serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

tango_with_django_project/rango/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    @staticmethod
    def encode(name):
        return name.replace(' ', '_')

    @staticmethod
    def decode(name):
        return name.replace('_', ' ')

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def category_name(self):
        return self.category.name
    category_name.short_description = 'Category'

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User
from django import forms

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://', prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them...
        # Here, we are hiding the foreign key.
        fields = ('title', 'url', 'views')

class UserForm(forms.ModelForm):
    username = forms.CharField(help_text="Please enter a username.")
    email = forms.CharField(help_text="Please enter your email.")
    password = forms.CharField(widget=forms.PasswordInput(), help_text="Please enter a password.")

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(help_text="Please enter your website.", required=False)
    picture = forms.ImageField(help_text="Select a profile image to upload.", required=False)

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

tango_with_django_project/rango/views.py
from django.template import RequestContext
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime
from rango.models import Category
from rango.models import Page, UserProfile
from rango.forms import CategoryForm
from rango.forms import PageForm
from rango.forms import UserForm, UserProfileForm

#helper function to get category list
def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)
    else:
        cat_list = Category.objects.all()

    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]

    for cat in cat_list:
        cat.url = Category.encode(cat.name)

    return cat_list

# Create your views here.
def index(request):
    # Request the context of the request.
    # The context contains information such as the client's machine details, for example.
    #context = RequestContext(request)
    # NOT ANYMORE WITH RENDER

    # Query the database for a list of ALL categories currently stored.
    # Order the categories by no. likes in descending order.
    # Retrieve the top 5 only - or all if less than 5.
    # Place the list in our context_dict dictionary which will be
    # passed to the template engine.
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    cat_list = get_category_list()
    context_dict = {'categories': category_list, 'pages': page_list,
                    'cat_list': cat_list}
    # The following two lines are new.
    # We loop through each category returned, and create a URL
    # attribute. This attribute stores an encoded URL (e.g. spaces
    # replaced with underscores).
    for category in category_list:
        category.url = Category.encode(category.name)

    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.

     # Get the number of visits to the site.
    # We use the COOKIES.get() function to obtain the visits cookie.
    # If the cookie exists, the value returned is casted to an integer.
    # If the cookie doesn't exist, we default to zero and cast that.
    visits = int(request.COOKIES.get('visits', '0'))
    if request.session.get('last_visit'):
        # The session has a value for The last visit
        last_visit_time = request.session.get('last_visit')
        visits = request.session.get('visits', 0)

        if (datetime.now() - datetime.strptime(last_visit_time[:-7], "%Y-%m-%d %H:%M:%S")).days > 0:
            request.session['visits'] = visits + 1
            request.session['last_visit'] = str(datetime.now())
    else:
        # The get returns None, and the session does not have a value for the last visit.
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = 1

    # Return response back to the user, updating any cookies that need
    # changed.
    response = render(request, 'rango/index.html', context_dict)
    return response

def about(request):
    #context = RequestContext(request)
    # NOT ANYMORE WITH RENDER
    if request.session.get('visits'):
        count = request.session.get('visits')
    else:
        count = 0
    about_string = "Stalin es el mejon. Repitelo " + str(count) + "veces"
    cat_list = get_category_list()
    context_dictionary = {'aboutmessage': about_string, 'cat_list':
                          cat_list }

    return render(request, 'rango/about.html', context_dictionary)

def category(request, category_name_url):
     # Request our context from the request passed to us.
    #context = RequestContext(request)
    # NOT ANYMORE WITH RENDER

    # Change underscores in the category name to spaces.
    # URLs don't handle spaces well, so we encode them as underscores.
    # We can then simply replace the underscores with spaces again to
    # get the name.
    category_name = Category.decode(category_name_url)

    # Create a context dictionary which we can pass to the template
    # rendering engine. We start by containing the name of the
    # category passed by the user.
    cat_list = get_category_list()
    context_dict = {'category_name': category_name, 'cat_list':
                    cat_list}
    context_dict['category_name_url'] = category_name_url
    try:
        # Can we find a category with the given name?
        # If we can't, the .get() method raises a DoesNotExist
        # exception. So the .get() method returns one model instance
        # or raises an exception.
        category = Category.objects.get(name=category_name)

        # Retrieve all of the associated pages.
        # Note that filter returns >= 1 model instance.
        pages = Page.objects.filter(category=category)

        # Adds our results list to the template context under name
        # pages.
        context_dict['pages'] = pages

        # We also add the category object from the database to the
        # context dictionary. We'll use this in the template to verify
        # that the category exists.
        context_dict['category'] = category

        #Adding likes of category to context dictionary
        context_dict['category_likes'] = category.likes
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything - the template displays the "no category"
        # message for us.
        return add_category(request)

    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context_dict)

@login_required
def like_category(request):
    results = 0
    if request.method == 'GET':
        if 'category_id' in request.GET:
            category_id = request.GET['category_id']
            category = Category.objects.get(pk=category_id)
            if category:
                category.likes = category.likes + 1
                category.save()
                results = category.likes

    return HttpResponse(results)

@login_required
def add_category(request):
    #A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)

            # Now call the index() view.
            # The user will be shown the homepage.
            return index(request)
        else:
            # The supplied form contained errors - just print them to the terminal.
            print(form.errors)
    else:
        # If the request was not a POST, display the form to enter details.
        form = CategoryForm()

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_url):

    category_name = Category.decode(category_name_url)
    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            # This time we cannot commit straight away.
            # Not all fields are automatically populated!
            page = form.save(commit=False)

            # Retrieve the associated Category object so we can add it.
            # Wrap the code in a try block - check if the category actually exists!
            try:
                cat = Category.objects.get(name=category_name)
                page.category = cat
            except Category.DoesNotExist:
                # If we get here, the category does not exist.
                # Go back and render the add category form as a way of saying the category does not exist.
                return render(request, 'rango/add_category.html', {})

            # Also, create a default value for the number of views.
            page.views = 0

            # With this, we can then save our new model instance.
            page.save()

            # Now that the page is saved, display the category instead.
            return category(request, category_name_url)
        else:
            print(form.errors)
    else:
        form = PageForm()

    cat_list = get_category_list()
    return render(request, 'rango/add_page.html',
            {'category_name_url': category_name_url,
             'category_name': category_name, 'cat_list': cat_list,
             'form': form})


def register(request):
    # Like before, get the request's context.
    #context = RequestContext(request)

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Rango's About{% endblock %}
{% block body_block %}
    <div class="hero-unit">
      <h1>Rango says...</h1>
      hello about page! <strong>{{ aboutmessage }}</strong><br />

      <img src="{% static "stalin.jpg" %}" alt="Picture of a great leader" />
    </div>
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title %}Rango{% endblock %}

{% block body_block %}
<div class="hero-unit">
  <h1>Add a Category</h1>
  <br/>
  <div class="container">
    <form class="span6" id="category_form" method="post" action="/rango/add_category/">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
      {{ hidden }}
      {% endfor %}

      {% for field in form.visible_fields %}
      {{ field.errors }}
      {{ field.help_text }}<br/>
      {{ field }}
      {% endfor %}

      <br/>
      <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
    </form>
  </div>
</div>
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title %}Rango{% endblock %}

{% block body_block %}
<div class="hero-unit">
  <h1>Add a Page</h1>
  <br/>
  <div class="container">
    <form class="span6" id="category_form" method="post" action="/rango/add_page/">

    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}
    {{ field }}
    {% endfor %}
    <br/>
    <button class="btn btn-primary" type="submit" name="submit"/>Create Page</button>
  </form>
  </div>
</div>
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap-fluid-adj.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
    <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/rango/">Rango</a>

           <div class="nav-collapse collapse">
             <ul class="nav pull-right">
               {% if user.is_authenticated %}
               <li class="navbar-text">Welcome, {{ user.username }}!</li>
               <li><a href="{% url 'rango:logout' %}">Logout</a></li>
               {% else %}
               <li><a href="{% url 'rango:register' %}">Register</a></li>
               <li><a href="{% url 'rango:login' %}">Login</a></li>
               {% endif %}
             </ul>
             <ul class="nav">
               {% if user.is_authenticated %}
               <li><a href="{% url 'rango:restricted' %}">Restricted</a></li>
               <li><a href="{% url 'rango:add_category' %}">Add Category</a></li>
               <li><a href="{% url 'rango:profile' %}">Profile</a></li>
               {% endif %}
               <li><a href="{% url 'rango:about' %}">About</a></li>
             </ul>
           </div>
           <!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <!--- Empty for the timebeing -->
            <ul class="nav nav-list">
              <li class="nav-header">Find a Category</li>
              <form>
                <label></label>
                <li><input  class="search-query span10" type="text" name="suggestion" value="" id="suggestion" /></li>
              </form>
            </ul>
            {% if cat_list %}
            <div id="cats">
              {% include 'rango/category_list.html' %}
            </div>
            {% endif %}
          </div>
          <!--/.well -->
        </div>
        <!--/span-->
        <div class="span9">
          {% block body_block %}
          {% endblock %}
        </div>
        <!--/span-->
      </div>
      <!--/row-->
    </div>
    <!--/.fluid-container-->

    <hr>

    <footer>
      <div class="container">
        <p>&copy; Rango: How to Tango with Django 2014</p>
      </div>
    </footer>
    <script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/rango-ajax.js' %}"></script>
  </body>
</html>

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
<!--
<div class="container-fluid">
  <form class="form-signin span8" id="user_form" method="post" action="/rango/search/">
    {% csrf_token %}
    <!-- Display the search form elements here
    <input type="text" size="50" name="query" value="" id="query" />
    <input class="btn btn-primary" type="submit" name="submit" value="Search" />
    <br />
  </form>

  {% if result_list %}
  <!-- Display search results in an ordered list
  <div style="clear: both;">
    <ol>
      {% for result in result_list %}
      <li>
        <strong><a href="{{ result.link }}">{{ result.title }}</a></strong><br />
        <em>{{ result.summary }}</em>
      </li>
      {% endfor %}
    </ol>
  </div>
  {% endif %}
</div>
-->

<div class="hero-unit">
  <h1>{{ category_name }}</h1>
  {% if category %}
  {% if pages %}
  <ul>
    {% for page in pages %}
    <li><a href="{% url 'rango:track_url' %}?page_id={{page.pk}}">{{ page.title }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
  <strong>No pages currently in category.</strong>
  {% endif %}

  <div>
    <p>

      <b id="like_count">{{ category_likes }}</b> people like this category

      {% if user.is_authenticated %}
      <button id="likes" data-catid="{{ category.id }}" class="btn btn-mini btn-primary" type="button">Like</button>
      {% endif %}

    </p>
  </div>
  {% if user.is_authenticated %}
  <a href="{% url 'rango:add_page' category_name_url %}">Create Page</a>
  {% endif %}
  {% else %}
  The specified category {{ category_name }} does not exist!
  {% endif %}
</div>
{% endblock %}

tango_with_django_project/templates/rango/category_list.html
<div class="span6">
  <h2>Categories</h2>
  {% if cat_list %}
  <ul>
    {% for category in cat_list %}
    <li><a href="/rango/category/{{ category.url }}">{{ category.name }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
  <strong>No categories at present.</strong>
  {% endif %}
</div>

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html'%}

{% load staticfiles %}

{% block title %}Rango{% endblock %}

{% block body_block %}
<div class="hero-unit">
  <h1>Ready to Rango</h1>
  <p>Find, Add, Share and Rango useful links and resources.</p>
</div>

<div class="row-fluid">
  <div class="span6">
    <h2>Top Five Categories</h2>
    {% if categories %}
    <ul>
      {% for category in categories %}
      <li><a href="/rango/category/{{ category.url }}">{{ category.name }}</a></li>
      {% endfor %}
    </ul>
    {% else %}
    <strong>No categories at present.</strong>
    {% endif %}

  </div>
  <!--/span-->
  <div class="span6">
    <h2>Top Five Pages</h2>
    {% if pages %}
    <ul>
      {% for page in pages %}
      <li><a href="{{ page.url}}">{{ page.title }}</a> - {{ page.category }} ({{ page.views }} view(s))</li>
      {% endfor %}
    </ul>
    {% else %}
    <strong>No pages at present.</strong>
    {% endif %}

  </div>
  <!--/span-->
</div>
<!--/row-->
{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends 'rango/base.html' %}

{% block body_block %}
<div class="hero-unit">
  <h1>Login to Rango</h1>

  <div class="container">
    <form class="form-signin span4" id="login_form" method="post" action="/rango/login/">
      <h2 class="form-signin-heading">Please sign in</h2>
      {% csrf_token %}

      {% if bad_details %}
      <p><strong>Your username and/or password were incorrect!</strong></p>
      {% elif disabled_account %}
      <p><strong>Your Rango account is currently disabled; we can't log you in!</strong></p>
      {% endif %}

      Username: <input type="text" class="input-block-level" placeholder="Username" name="username" value="" size="50" />
      <br />
      Password: <input type="password" class="input-block-level" placeholder="Password" name="password" value="" size="50" />
      <br />
      <button class="btn btn-primary" type="submit">Sign in</button>
    </form>

  </div>
  <!-- /container -->
</div>
{% endblock %}

tango_with_django_project/templates/rango/profile.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}Rango{% endblock %}

{% block body_block %}
<div class="hero-unit">
  <h1>User Profile</h1>
  <ul>
    <li><b>Username:</b>{{ username }}</li>
    <li><b>email</b>{{ email }}</li>
    <li><b>Website</b><a href="{{ website }}">{{ website }}</li>
  </ul>
  {% if user_picture %}
     <img src="{{ MEDIA_URL }}{{ user_picture }}" alt="User Profile Picture" />
  {% endif %}
</div>
{% endblock %}

tango_with_django_project/templates/rango/register.html
{% extends 'rango/base.html' %}

{% block title %}Rango{% endblock %}

{% block body_block %}
<div class="hero-unit">
  <h1>Register with Rango</h1>

  <div class="container">
  {% if registered %}
  Rango says: <strong>thank you for registering!</strong>
  <a href="/rango/">Return to the homepage.</a><br />
  {% else %}
  Rango says: <strong>register here!</strong><br />

  <form id="user_form" method="post" action="/rango/register/"
        enctype="multipart/form-data">

    {% csrf_token %}
    <h2 class="form-signin-heading">Sign up Here</h2>
    <!-- Display each form here -->


    {% for field in user_form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}<br />
    {{ field }}<br />
    {% endfor %}

    {% for field in profile_form.visible_fields %}
    {{ field.errors }}
        {{ field.help_text }}<br />
    {{ field }}<br />
    {% endfor %}

    <br />
    <!-- Provide a button to click to submit the form. -->
    <input class="btn btn-primary" type="submit" name="submit" value="Register"/>
  </form>
  {% endif %}
  </div>
</div>
{% endblock %}

tango_with_django_project/templates/rango/restricted.html
{% extends 'rango/base.html' %}

{% block body_block %}
<div class="hero-unit">
  <h1>{{ restricted_msg }}</h1>
</div>
{% endblock %}